[[welcome-index]]
= {product-title} Documentação {product-version}
{product-author}
{product-version}
:data-uri:
:icons:

[.lead]
Bem-vindos à documentação do grupo {product-title}, onde você pode achar
informações e guias sobre os {product-title} e começar explorar as tecnologias que utilizamos.

Guardians é um grupo composto por alunos voluntários do curso de Ciência da Computação, da Universidade
Federal de Campina Grande. Os principais objetivos do grupo são: manter o funcionamento dos laboratórios
de ensino do curso, suporte aos usuários e às máquinas dos laboratórios, atualizações de segurança,
correção de falhas, desenvolvimento de novas aplicações, aquisição e disseminação de conhecimento
sobre **Administração de Sistemas**.


[IMPORTANT]
====
{product-title} {product-version} is community supported only.
====


[TIP]
====
Use o menu da esquerda para navegar na documentação, o campo de busca na parte
superior à esquerda para procurar algo em específico, ou os links abaixo para
acessar algo em destaque.
====

ifdef::openshift-origin[]
'''
[cols="2",frame="none",grid="none"]
|===

.^|[big]#Entre em contato#
a|[none]

* link:https://docs.google.com/forms/d/e/1FAIpQLSfJFJJKBwznlNYLBl-NVgIu-SQFqert2wkzJMs4tlMrAYnJsQ/viewform?formkey=dHBKRV9oeU43bVEzVDMzMWZiY2dJRWc6MQ#gid=0[Helpdesk]
* link:mailto:guardians-l@googlegroups.com[Email]

|===


'''
[cols="2",frame="none",grid="none"]
|===

.^|[big]#Redes Sociais#
a|[none]

* link:https://github.com/guardians-dsc/[Encontre todos nossos projetos no GitHub]
* link:https://www.facebook.com/guardiansufcg[Facebook]


|===
