[[welcome-index]]
= {product-title} Documentação {product-version}
{product-author}
{product-version}
:data-uri:
:icons:

[.lead]
Bem-vindos à documentação do grupo {product-title}, onde você pode achar
informações e guias sobre os {product-title} e começar explorar as tecnologias que utilizamos.

= Guardians?
[.text-justify]
Guardians é um grupo composto por alunos voluntários do curso de Ciência da Computação, da Universidade
Federal de Campina Grande. Os principais objetivos do grupo são: manter o funcionamento dos laboratórios
de ensino do curso, suporte aos usuários e às máquinas dos laboratórios, atualizações de segurança,
correção de falhas, desenvolvimento de novas aplicações, aquisição e disseminação de conhecimento
sobre **Administração de Sistemas**.

= Nossa Missão
[.text-justify]
Os Guardians têm como missão disseminar o conhecimento e atuar na manutenção/gerenciamento dos LCCs (Laboratórios de Ciência da Computação).

- adicionar aqui informações sobre como fazemos;

= Nossa Filosofia

[NOTE]
====
Este tópico contém informações retiradas do site link:https://sites.google.com/a/computacao.ufcg.edu.br/guardians-ccc/sobre[Guardians-ccc].
====

[.text-justify]
A estrutura organizacional adotada pelo grupo é horizontal, apostando no gerenciamento colaborativo, assim, não há
hierarquia entre os integrantes e as decisões são tomadas em conjunto. As atividades atribuídas ao grupo são realizadas de
acordo com a disponibilidade e conhecimento dos membros, nenhuma é direcionada para um integrante específico, os alunos
voluntariam-se para concretizá-la. Além disso, a equipe busca sempre melhorar os serviços prestados e estreitar o contato com
os estudantes que utilizam os laboratórios.

[TIP]
====
Use o menu da esquerda para navegar na documentação, o campo de busca na parte
superior à esquerda para procurar algo em específico, ou os links abaixo para
acessar algo em destaque.
====

ifdef::openshift-origin[]
'''
[cols="2",frame="none",grid="none"]
|===

.^|[big]#Entre em contato#
a|[none]

* link:https://docs.google.com/forms/d/e/1FAIpQLSfJFJJKBwznlNYLBl-NVgIu-SQFqert2wkzJMs4tlMrAYnJsQ/viewform?formkey=dHBKRV9oeU43bVEzVDMzMWZiY2dJRWc6MQ#gid=0[Helpdesk]
* link:mailto:guardians-l@googlegroups.com[Email]

|===


'''
[cols="2",frame="none",grid="none"]
|===

.^|[big]#Redes Sociais#
a|[none]

* link:https://github.com/guardians-dsc/[Encontre todos nossos projetos no GitHub]
* link:https://www.facebook.com/guardiansufcg[Facebook]


|===
